title:  "Yiruitian"
tagline: "a Jekyll theme"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
# - {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
# - {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Video', folder: 'pages', file: 'video.html'}
- {name: 'Design', folder: 'pages', file: 'design.html'}
- {name: 'Gif', folder: 'pages', file: 'gif.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Resume', folder: 'pages', file: 'resume.html'}

social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://www.instagram.com/yirui3751/'}
- {icon: 'vimeo', link: 'https://vimeo.com/user33173109'}
# - {icon: 'weibo', link: 'https://vimeo.com/user33173109'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
